name: Super-Linter

on: push

jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:

      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: make install

        env:
          CI: true
      - name: run linter
        run: make lint

      - name: run test
        run: make test